apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: chainlink-node
    app.kubernetes.io/name: chainlink
  name: chainlink-node
  namespace: chainlink-prod
spec:
  ports:
    - name: api
      port: 6688
      protocol: TCP
      targetPort: 6688
    - name: p2pv2
      port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    app.kubernetes.io/instance: chainlink-node
    app.kubernetes.io/name: chainlink
  type: ClusterIP
