apiVersion: v1
kind: Secret
metadata:
  name: chainlink-node-file
  namespace: chainlink-prod
stringData:
  api-secrets.toml: SessionSecret = "test-secret"
  apicredentials: |-
    admin@chain.link
    staticlongpassword
  secrets.toml: "[Password]\nKeystore = \"keystorepassword\"\nVRF = \"vrfpassword\"\n\n[Database]\nURL = \"postgresql://chainlink:password@postgres:5432/chainlink\""
type: Opaque
