apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: test-chainlink
    app.kubernetes.io/name: chainlink
  name: test-chainlink
  namespace: test-namespace
spec:
  ports:
    - name: api
      port: 6688
      protocol: TCP
      targetPort: 6688
    - name: p2pv2
      port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    app.kubernetes.io/instance: test-chainlink
    app.kubernetes.io/name: chainlink
  type: ClusterIP
