apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: custom-port-node
    app.kubernetes.io/name: chainlink
  name: custom-port-node
  namespace: test-namespace
spec:
  ports:
    - name: api
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: p2pv2
      port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    app.kubernetes.io/instance: custom-port-node
    app.kubernetes.io/name: chainlink
  type: ClusterIP
