apiVersion: v1
kind: Secret
metadata:
  name: auto-postgres-node-file
  namespace: test-namespace
stringData:
  apicredentials: |-
    admin@chain.link
    staticlongpassword
  secrets.toml: "[Password]\nKeystore = \"keystorepassword\"\nVRF = \"vrfpassword\"\n\n[Database]\nURL = \"postgresql://auto-postgres-node:staticlongpassword@auto-postgres-node-postgres:5432/auto-postgres-node?sslmode=disable\""
type: Opaque
