apiVersion: v1
data:
  password: c3RhdGljbG9uZ3Bhc3N3b3Jk
  postgres-password: c3RhdGljbG9uZ3Bhc3N3b3Jk
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: auto-postgres-node-postgres
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.5.0
    helm.crib.sdk/chart: postgresql
    helm.crib.sdk/name: postgresql
    helm.crib.sdk/namespace: test-namespace
    helm.crib.sdk/release: auto-postgres-node-postgres
    helm.sh/chart: postgresql-16.7.10
  name: auto-postgres-node-postgres
  namespace: test-namespace
type: Opaque
