apiVersion: crib.smartcontract.com/v1alpha1
kind: ClientSideApply
metadata:
  name: sdk-composite-te-sdk-clientsideapply-851cb4a2-c857d635
  namespace: default
spec:
  action: telepresence
  args:
    - connect
    - --namespace
    - test-namespace
    - --mapped-namespaces
    - test-namespace
    - --manager-namespace
    - test-namespace
  onFailure: abort
