apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: traffic-manager
    app.kubernetes.io/name: traffic-manager
  name: traffic-manager
  namespace: test-namespace
