apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: traffic-manager
    app.kubernetes.io/name: traffic-manager
  name: traffic-manager
  namespace: test-namespace
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - services
      - pods
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - ""
    resourceNames:
      - traffic-manager
    resources:
      - configmaps
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - get
      - watch
  - apiGroups:
      - ""
    resourceNames:
      - test-namespace
    resources:
      - namespaces
    verbs:
      - get
