apiVersion: v1
data:
  client.yaml: "dns:\n  excludeSuffixes:\n  - .com\n  - .io\n  - .net\n  - .org\n  - .ru\n"
  namespace-selector.yaml: "matchExpressions:\n- key: kubernetes.io/metadata.name\n  operator: In\n  values:\n  - test-namespace\n"
kind: ConfigMap
metadata:
  labels:
    app: traffic-manager
    app.kubernetes.io/created-by: Helm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 2.23.3
    helm.crib.sdk/chart: telepresence-oss
    helm.crib.sdk/name: telepresence-oss
    helm.crib.sdk/namespace: test-namespace
    helm.crib.sdk/release: traffic-manager
    helm.sh/chart: telepresence-oss-2.23.3
    telepresence: manager
  name: traffic-manager
  namespace: test-namespace
