apiVersion: crib.smartcontract.com/v1alpha1
kind: ClientSideApply
metadata:
  name: sdk-composite-te-sdk-clientsideapply-4fd1e062-c88fca48
  namespace: test-namespace
spec:
  action: telepresence
  args:
    - quit
    - --stop-daemons
  onFailure: abort
