apiVersion: crib.smartcontract.com/v1alpha1
kind: ClientSideApply
metadata:
  name: testingapp-5b9bc-sdk-clientsideapply-1106cfe7-c8832ad9
  namespace: default
spec:
  action: telepresence
  args:
    - connect
  onFailure: abort
