apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: test-jd
    app.kubernetes.io/name: jd
  name: test-jd
  namespace: test-namespace
spec:
  ports:
    - name: grpc
      port: 42242
      protocol: TCP
      targetPort: 42242
    - name: wsrpc
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: wsrpc-health
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-jd
    app.kubernetes.io/name: jd
  type: ClusterIP
