apiVersion: crib.smartcontract.com/v1alpha1
kind: ClientSideApply
metadata:
  name: sdk.anvilcomposi-sdk.clientsideapply-20d8c19b-c85e4cc5
  namespace: e2e-create-plan
spec:
  action: kubectl
  args:
    - rollout
    - status
    - deployment
    - -l
    - app.kubernetes.io/instance=anvil-e2e-create-plan
    - --timeout=600s
  onFailure: abort
