apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: anvil-e2e-create-plan
    app.kubernetes.io/name: anvil
  name: anvil-e2e-create-plan
  namespace: e2e-create-plan
spec:
  ports:
    - port: 8545
      protocol: TCP
      targetPort: 8545
  selector:
    app.kubernetes.io/instance: anvil-e2e-create-plan
    app.kubernetes.io/name: anvil
  type: ClusterIP
