---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj # codespell:ignore fo

version: '3'

tasks:
  tools:
    run: once
    desc: Use asdf to install the tools defined in .tool-versions.
    cmds:
      - awk '{print $1}' .tool-versions | xargs -P 8 -I _ asdf plugin add _
      - awk '{print $1, $2}' .tool-versions | xargs -P 8 -n 2 asdf install $1 $2
      - awk '{print $1, $2}' .tool-versions | xargs -n 2 asdf set $1 $2
    preconditions:
      - sh: command -v asdf > /dev/null
        msg: "asdf is not installed. Please install asdf and try again."

  pre-commit:
    desc: Install pre-commit hooks.
    cmds:
      - pre-commit install
    preconditions:
      - sh: command -v pre-commit > /dev/null
        msg: "pre-commit is not installed. Please run task install:tools to configure it."
