// Code generated by cribctl; DO NOT EDIT.
//
// File can be regenerated with:
//
//		cribctl helm create-component \
//	 	otterscan \
//	     component-chart@https://charts.devspace.sh \
//	     --version=0.9.1 \
//	     --no-clobber
//
//lint:file-ignore ST1000,U1000 This file is generated by go generate.
package otterscan

import (
	"testing"
	
	"github.com/stretchr/testify/require"

	"github.com/smartcontractkit/crib-sdk/crib/scalar/helmchart/v1"
	"github.com/smartcontractkit/crib-sdk/internal"
)

func TestChartComponent_otterscan(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping test in short mode.")
	}
	t.Parallel()
	app := internal.NewTestApp(t)
	must := require.New(t)

	loader, err := internal.NewHelmValuesLoader(app.Context(), "testdata")
	if err != nil {
		t.Logf("[Important] Unable to run tests for HelmChart %s, the required test data is missing.", chartName)
		t.SkipNow()
	}

	props := &helmchart.ChartProps{
		Namespace:    "test-ns-" + chartName,
		ValuesLoader: loader,
	}

	component, err := Component(props)(app.Context())
	must.NoError(err)
	must.NotNil(component)

	app.SynthYaml()
}
