apiVersion: v1
automountServiceAccountToken: false
imagePullSecrets:
  - name: pull-secret1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: test-instance
    app.kubernetes.io/name: test-app
  name: full-service-account
  namespace: test-namespace
secrets:
  - name: secret1
  - name: secret2
