apiVersion: v1
kind: Service
metadata:
  annotations:
    helm.sh/chart: component-chart-0.9.1
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: loki
    helm.crib.sdk/chart: component-chart
    helm.crib.sdk/name: helm-loki
    helm.crib.sdk/namespace: ns-loki
    helm.crib.sdk/release: loki
  name: loki
  namespace: ns-loki
spec:
  ports:
    - name: port-0
      port: 3100
      protocol: TCP
      targetPort: 3100
  selector:
    app.kubernetes.io/component: loki
    app.kubernetes.io/name: devspace-app
  type: ClusterIP
