apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    helm.sh/chart: component-chart-0.9.1
  labels:
    app.kubernetes.io/component: loki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: devspace-app
    helm.crib.sdk/chart: component-chart
    helm.crib.sdk/name: helm-loki
    helm.crib.sdk/namespace: ns-loki
    helm.crib.sdk/release: loki
  name: loki
  namespace: ns-loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: loki
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: devspace-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        helm.sh/chart: component-chart-0.9.1
      labels:
        app.kubernetes.io/component: loki
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: devspace-app
    spec:
      containers:
        - args:
            - --config.file=/etc/loki/config/loki.yml
          image: grafana/loki:3.1.0
          name: container-0
          volumeMounts:
            - mountPath: /etc/loki/config
              name: config-volume
              readOnly: false
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      terminationGracePeriodSeconds: 5
      volumes:
        - configMap:
            name: loki-config
          name: config-volume
