apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    helm.sh/chart: component-chart-0.9.1
  labels:
    app.kubernetes.io/component: ots-1337
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: devspace-app
    helm.crib.sdk/chart: component-chart
    helm.crib.sdk/name: component-chart
    helm.crib.sdk/namespace: test-ns-otterscan
    helm.crib.sdk/release: ots-1337
  name: ots-1337
  namespace: test-ns-otterscan
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: ots-1337
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: devspace-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        helm.sh/chart: component-chart-0.9.1
      labels:
        app.kubernetes.io/component: ots-1337
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: devspace-app
    spec:
      containers:
        - env:
            - name: ERIGON_URL
              value: http://anvil-1337:8545
          image: otterscan/otterscan:latest
          name: container-0
      terminationGracePeriodSeconds: 5
