apiVersion: v1
kind: Service
metadata:
  annotations:
    helm.sh/chart: component-chart-0.9.1
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ots-1337
    helm.crib.sdk/chart: component-chart
    helm.crib.sdk/name: component-chart
    helm.crib.sdk/namespace: test-ns-otterscan
    helm.crib.sdk/release: ots-1337
  name: ots-1337
  namespace: test-ns-otterscan
spec:
  ports:
    - name: port-0
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/component: ots-1337
    app.kubernetes.io/name: devspace-app
  type: ClusterIP
