apiVersion: v1
data:
  key1: value1
  key2: value2
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: test-app-123
    app.kubernetes.io/name: test-app
  name: cm-1
  namespace: default
