apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: blockchain-1234
    app.kubernetes.io/name: blockchain
  name: blockchain-1234
  namespace: test-ns
spec:
  ports:
    - port: 8545
      protocol: TCP
      targetPort: 8545
  selector:
    app.kubernetes.io/instance: blockchain-1234
    app.kubernetes.io/name: blockchain
  type: ClusterIP
