apiVersion: apps/v1
kind: Deployment
metadata:
  name: testchart-test-deployment-c8297cd2
spec:
  selector:
    matchLabels:
      app: test
  template:
    spec:
      containers:
        - name: test-container
      imagePullSecrets:
        - name: test-secret
