apiVersion: v1
kind: Service
metadata:
  annotations:
    helm.sh/chart: component-chart-0.9.1
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jd
    helm.crib.sdk/chart: component-chart
    helm.crib.sdk/name: component-chart
    helm.crib.sdk/namespace: test-ns-jd
    helm.crib.sdk/release: jd
  name: jd
  namespace: test-ns-jd
spec:
  ports:
    - name: grpc
      port: 42242
      protocol: TCP
      targetPort: 42242
    - name: wsrpc
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: wsrpc-health
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/component: jd
    app.kubernetes.io/name: devspace-app
  type: ClusterIP
