apiVersion: v1
kind: Service
metadata:
  annotations:
    foo: bar
  labels:
    app.kubernetes.io/instance: test-app-123
    app.kubernetes.io/name: test-app
  name: web-service
  namespace: production
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: web
  type: ClusterIP
