---
name: "Release Please"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write # Required for release-please to apply labels to PRs.

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        id: release
        with:
          # Use configuration files instead of inline config
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
